# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BackTest_CP.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 207)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(560, 160, 93, 28))
        self.pushButton.setObjectName("Start")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 27, 93, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        # self.pushButton_3.setGeometry(QtCore.QRect(560, 87, 93, 31))
        # self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(230, 30, 311, 22))
        self.lineEdit.setObjectName("lineEdit")
        # self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        # self.lineEdit_2.setGeometry(QtCore.QRect(230, 90, 311, 22))
        # self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 211, 16))
        self.label.setObjectName("label")
        # self.label_2 = QtWidgets.QLabel(Dialog)
        # self.label_2.setGeometry(QtCore.QRect(40, 90, 181, 16))
        # self.label_2.setObjectName("label_2")

        self.progress = QtWidgets.QProgressBar(Dialog)
        self.progress.setGeometry(230, 160, 320, 22)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "error check"))
        self.pushButton.setText(_translate("Dialog", "Run"))
        self.pushButton_2.setText(_translate("Dialog", "Find"))
        # self.pushButton_3.setText(_translate("Dialog", "Find"))
        self.label.setText(_translate("Dialog", "Select path to .xlsx file"))
        # self.label_2.setText(_translate("Dialog", "Select path to result folder"))
